on:
  push:
    tags:
      - "v*"
name: Release
jobs:
  build:
    name: Release (github.com)
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: fw
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: cargo build --release
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: musl-strip target/x86_64-unknown-linux-musl/release/fw
      - run: cp ./target/x86_64-unknown-linux-musl/release/fw fw
      - run: sha512sum fw > fw.sha512sum
      - run: cargo run >> fw.1
        working-directory: ./man
      - id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: |
            fw
            man/fw.1
            fw.sha512sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

