on:
  push:
    tags:
      - "v*"
name: Release
jobs:
  build:
    name: Release (github.com)
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: fw
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: cargo build --release
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: musl-strip target/x86_64-unknown-linux-musl/release/fw
      - run: cp ./target/x86_64-unknown-linux-musl/release/fw fw
      - run: sha512sum fw > fw.sha512sum
      - run: cd src/man
      - run: cargo run >> target/fw.1
      - id: github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release fw ${{ github.ref }}
          body: "No changelog!"
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: ./fw
          asset_name: fw
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: ./man/target/fw.1
          asset_name: fw.1
          asset_content_type: text/plain
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: ./fw.sha512sum
          asset_name: fw.sha512sum
          asset_content_type: text/plain
